#!/usr/bin/env python3
"""Generate cargo-dist 0.31.0 CI with a strict, pre-plan publication gate."""

import argparse
from pathlib import Path
import shutil
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parent.parent
WORKFLOW = Path('.github/workflows/release.yml')


def replace_once(text, before, after):
    if text.count(before) != 1:
        raise ValueError(f'cargo-dist template changed: expected exactly one {before!r}')
    return text.replace(before, after, 1)


def gate(text):
    text = replace_once(text, '# This file was autogenerated by dist: https://axodotdev.github.io/cargo-dist\n',
                        '# This file was autogenerated by dist: https://axodotdev.github.io/cargo-dist\n'
                        '# Regenerate with python3 scripts/generate-release-workflow.py (dist 0.31.0).\n')
    # plan can invoke dist host --steps=create: checks must precede even that.
    text = replace_once(text, '  plan:\n',
                        "  plan:\n    needs: [custom-checks]\n"
                        "    if: ${{ needs.custom-checks.result == 'success' }}\n")
    text = replace_once(text, '  host:\n    needs:\n',
                        '  host:\n    needs:\n      - custom-checks\n')
    text = replace_once(text, "if: ${{ always() && needs.plan.result == 'success'",
                        "if: ${{ always() && needs.custom-checks.result == 'success'"
                        " && needs.plan.result == 'success'")
    # All source jobs use the event's immutable commit, as does the check hook.
    text = text.replace('          submodules: recursive\n',
                        '          submodules: recursive\n          ref: ${{ github.sha }}\n')
    return text


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    version = subprocess.check_output(['dist', '--version'], text=True).strip()
    if version != 'cargo-dist 0.31.0':
        raise ValueError(f'expected dist 0.31.0, got {version}')
    # Generate in test-owned state; checking never rewrites the real workflow.
    with tempfile.TemporaryDirectory(prefix='flicknote-release-ci-') as directory:
        checkout = Path(directory)
        files = subprocess.check_output(['git', 'ls-files', '-z'], cwd=ROOT).decode().split('\0')
        for name in filter(None, files):
            source = ROOT / name
            if source.is_file():
                target = checkout / name
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(source, target)
        config = checkout / 'dist-workspace.toml'
        config.write_text(replace_once(config.read_text(), 'allow-dirty = ["ci"]',
                                       'allow-dirty = []'))
        subprocess.run(['dist', 'generate', '--mode', 'ci'], cwd=checkout, check=True)
        expected = gate((checkout / WORKFLOW).read_text())
    if args.check:
        if (ROOT / WORKFLOW).read_text() != expected:
            raise ValueError('release workflow differs; run scripts/generate-release-workflow.py')
        print('Release workflow generation matches; publication requires successful exact-source checks.')
    else:
        (ROOT / WORKFLOW).write_text(expected)


if __name__ == '__main__':
    main()
