clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false
      depth: 0

when:
  - event: pull_request

steps:
  - name: check
    image: ghcr.io/tta-lab/moon-ci:latest
    commands:
      - |
        moon setup
        moon ci :fmt :lint :test :deny
